<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $i = 1;
        
        $permissions = [
            [
                'id'    => $i++,
                'title' => 'user_management_access',
                'type' => 'role.user.audit_log',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'permission_create',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'permission_edit',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'permission_show',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'permission_delete',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'permission_access',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_create',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_edit',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_show',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_delete',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_access',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_create',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_edit',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_show',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_delete',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_access',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'audit_log_show',
                'type' => 'audit_log',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'audit_log_access',
                'type' => 'audit_log',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_create',
                'type' => 'user_alert',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_show',
                'type' => 'user_alert',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_delete',
                'type' => 'user_alert',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_access',
                'type' => 'user_alert',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_create',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_edit',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_show',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_delete',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_access',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'frontend_setting_access',
                'type' => 'setting.slider.partner.said_about_us.humanitarian_aid',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_create',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_edit',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_show',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_delete',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_access',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkma_mangment_access',
                'type' => 'hawkam_category.hawkma',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkam_category_create',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkam_category_edit',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkam_category_show',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkam_category_delete',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkam_category_access',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkma_create',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkma_edit',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkma_show',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkma_delete',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'hawkma_access',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'post_create',
                'type' => 'post',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'post_edit',
                'type' => 'post',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'post_show',
                'type' => 'post',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'post_delete',
                'type' => 'post',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'post_access',
                'type' => 'post',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'partner_create',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'partner_edit',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'partner_show',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'partner_delete',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'partner_access',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'said_about_us_create',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'said_about_us_edit',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'said_about_us_show',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'said_about_us_delete',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'said_about_us_access',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'project_create',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'project_edit',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'project_show',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'project_delete',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'project_access',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteering_managment_access',
                'type' => 'volunteer.volunteer_guide',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_create',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_edit',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_show',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_delete',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_access',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_guide_create',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_guide_edit',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_guide_show',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_guide_delete',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'volunteer_guide_access',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'member_create',
                'type' => 'member',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'member_edit',
                'type' => 'member',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'member_show',
                'type' => 'member',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'member_delete',
                'type' => 'member',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'member_access',
                'type' => 'member',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'contact_mangment_access',
                'type' => 'contact.subscribe',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'contact_create',
                'type' => 'contact',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contact_edit',
                'type' => 'contact',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contact_show',
                'type' => 'contact',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contact_delete',
                'type' => 'contact',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contact_access',
                'type' => 'contact',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_create',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_edit',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_show',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_delete',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'subscribe_access',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'course_create',
                'type' => 'course',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_edit',
                'type' => 'course',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_show',
                'type' => 'course',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_delete',
                'type' => 'course',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_access',
                'type' => 'course',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_student_create',
                'type' => 'course_student',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_student_edit',
                'type' => 'course_student',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_student_show',
                'type' => 'course_student',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_student_delete',
                'type' => 'course_student',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'course_student_access',
                'type' => 'course_student',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'task_management_access',
                'type' => 'task_status.task_tag.task',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_create',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_edit',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_show',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_delete',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_status_access',
                'type' => 'task_status',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_create',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_edit',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_show',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_delete',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_tag_access',
                'type' => 'task_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_create',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_edit',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_show',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_delete',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'task_access',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'tasks_calendar_access',
                'type' => 'task',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'review_delete',
                'type' => 'review',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'review_access',
                'type' => 'review',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'report_mangment_access',
                'type' => 'report_category.report.report_money',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'report_category_create',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_category_edit',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_category_show',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_category_delete',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_category_access',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_create',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_edit',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_show',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_delete',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_access',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_money_create',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_money_edit',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_money_show',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_money_delete',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'report_money_access',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'humanitarian_aid_create',
                'type' => 'humanitarian_aid',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'humanitarian_aid_edit',
                'type' => 'humanitarian_aid',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'humanitarian_aid_show',
                'type' => 'humanitarian_aid',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'humanitarian_aid_delete',
                'type' => 'humanitarian_aid',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'humanitarian_aid_access',
                'type' => 'humanitarian_aid',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'donation_system_access',
                'type' => 'donation.beneficiary',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'donation_create',
                'type' => 'donation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'donation_edit',
                'type' => 'donation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'donation_show',
                'type' => 'donation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'donation_delete',
                'type' => 'donation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'donation_access',
                'type' => 'donation',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_create',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_edit',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_show',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_delete',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_access',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_status_specialist',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_status_manager',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'beneficiary_status_money',
                'type' => 'beneficiary',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'questionnaire_traning',
                'type' => 'questionnaire',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'questionnaire_volunteers',
                'type' => 'questionnaire',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'questionnaire_courses',
                'type' => 'questionnaire',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'questionnaire_certificate',
                'type' => 'questionnaire',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'questionnaire_members',
                'type' => 'questionnaire',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'questionnaire',
                'type' => 'questionnaire',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'memperships',
                'type' => 'memperships',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'profile_password_edit',
                'type' => 'profile_password',
                'parent' => 2,
            ],
        ];

        Permission::insert($permissions);
    }
}
